import "dotenv/config";
import { JiraAIResponse } from "./schema";

const JIRA_BASE_URL = process.env.JIRA_BASE_URL;
const JIRA_EMAIL = process.env.JIRA_EMAIL;
const JIRA_API_TOKEN = process.env.JIRA_API_TOKEN;
const DEFAULT_PROJECT_KEY = process.env.JIRA_PROJECT_KEY || "PB";
const EPIC_LINK_FIELD = process.env.JIRA_EPIC_LINK_FIELD || ""; // "parent" or "customfield_xxxxx"

if (!JIRA_BASE_URL || !JIRA_EMAIL || !JIRA_API_TOKEN) {
  console.warn(
    "⚠️ Jira config missing. Set JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY."
  );
}

const authHeader =
  JIRA_EMAIL && JIRA_API_TOKEN
    ? "Basic " + Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString("base64")
    : null;

function jiraHeaders() {
  if (!authHeader) {
    throw new Error("Jira auth not configured");
  }
  return {
    "Content-Type": "application/json",
    Authorization: authHeader,
    Accept: "application/json"
  };
}

// Simple ADF paragraph doc
function adfParagraphDoc(text: string): any {
  return {
    version: 1,
    type: "doc",
    content: [
      {
        type: "paragraph",
        content: text
          ? [
              {
                type: "text",
                text
              }
            ]
          : []
      }
    ]
  };
}

// Story description + Acceptance Criteria as bullet list (ADF)
function adfStoryDescriptionWithAC(story: {
  description: string;
  acceptance_criteria: string[];
}): any {
  const ac = story.acceptance_criteria || [];

  const acBlocks =
    ac.length > 0
      ? [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: "Acceptance Criteria:"
              }
            ]
          },
          {
            type: "bulletList",
            content: ac.map((line) => ({
              type: "listItem",
              content: [
                {
                  type: "paragraph",
                  content: [
                    {
                      type: "text",
                      text: line
                    }
                  ]
                }
              ]
            }))
          }
        ]
      : [];

  return {
    version: 1,
    type: "doc",
    content: [
      {
        type: "paragraph",
        content: [
          {
            type: "text",
            text: story.description
          }
        ]
      },
      ...acBlocks
    ]
  };
}

async function createIssue(fields: any) {
  const res = await fetch(`${JIRA_BASE_URL}/rest/api/3/issue`, {
    method: "POST",
    headers: jiraHeaders(),
    body: JSON.stringify({ fields })
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Jira create failed: ${res.status} - ${err}`);
  }

  return res.json(); // { id, key, ... }
}

export async function createEpicsAndStories(
  data: JiraAIResponse,
  projectKey?: string
) {
  if (!authHeader) {
    throw new Error("Jira auth not configured.");
  }

  const proj = projectKey || DEFAULT_PROJECT_KEY;
  const epicKeyBySummary: Record<string, string> = {};
  const createdStories: { key: string; summary: string }[] = [];

  // 1) Create Epics
  for (const epic of data.epics) {
    const epicFields: any = {
      project: { key: proj },
      summary: epic.summary,
      description: adfParagraphDoc(
        epic.description || "Epic generated by JiraAI."
      ),
      issuetype: { name: "Epic" },
      priority: { name: epic.priority }
    };

    const created = await createIssue(epicFields);
    epicKeyBySummary[epic.summary] = created.key;
  }

  // 2) Create Stories + link to epic (using configured field)
  for (const story of data.stories) {
    const storyFields: any = {
      project: { key: proj },
      summary: story.summary,
      description: adfStoryDescriptionWithAC(story),
      issuetype: { name: "Story" },
      priority: { name: story.priority }
    };

    const epicKey = epicKeyBySummary[story.epic_summary];

    if (epicKey && EPIC_LINK_FIELD) {
      if (EPIC_LINK_FIELD === "parent") {
        // Team-managed: parent is the epic key
        storyFields.parent = { key: epicKey };
      } else {
        // Company-managed: Epic Link custom field (e.g. customfield_10014)
        storyFields[EPIC_LINK_FIELD] = epicKey;
      }
    }

    const created = await createIssue(storyFields);
    createdStories.push({ key: created.key, summary: story.summary });
  }

  return { epicKeyBySummary, createdStories };
}
